version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env-prod
  redis:
    image: redis:7
    container_name: booking_redis

  bookings:
    build:
      context: .
    container_name: fastapi_bookings
    restart: unless-stopped
    env_file:
      - .env-prod
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    links:
      - db:db

  celery:
    build:
      context: .
    container_name: celery
    command: sh -c "celery --app=app.tasks.settings_celery:celery worker -l INFO"
    env_file:
      - .env-prod
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower
    command: sh -c "celery --app=app.tasks.settings_celery:celery flower"
    env_file:
      - .env-prod
    depends_on:
      - redis
    ports:
      - 5555:5555
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
      image: grafana/grafana:9.4.7
      container_name: grafana
      volumes:
        - grafanadata:/var/lib/grafana
      restart: unless-stopped
      ports:
        - 3000:3000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - EK-net
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image:  docker.elastic.co/kibana/kibana:7.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - EK-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:

networks:
  EK-net:
    driver: bridge