name: "Run Test"
on: push
jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          TEST_DB_HOST:localhost
          TEST_DB_PORT:5432
          TEST_DB_NAME:hotels
          TEST_DB_USER:postgres
          TEST_DB_PASSWORD:1234
          TEST_DATABASE_URL:postgresql+asyncpg://postgres:1234@127.0.0.1:5432/hotels_test_db
        ports:
          - 5432:5432
    steps:
      - name: get source code
        uses: actions/checkout@v4
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: install requirements
        run: python3 -m pip install -r requirements.txt
      - name: set enviroment variable on test
        run: export MODE='TEST'
      - name: run test
        run: pytest -v -s
