name: "Deploy"
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-name:
          - hotels_test_db
        database-password:
          - 1234
        database-user:
          - postgres
        database-host:
          - 127.0.0.1
        database-port:
          - 5432
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: get source code
        uses: actions/checkout@v4
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: install requirements
        run: python3 -m pip install -r requirements.txt
      - name: run test
        env:
          DATABASE_NAME_TEST: ${{ matrix.database-name }}
          DATABASE_USER: ${{ matrix.database-user }}
          DATABASE_PASSWORD: ${{ matrix.database-password }}
          DATABASE_HOST: ${{ matrix.database-host }}
          DATABASE_PORT: ${{ matrix.database-port }}
          POSTGRES_DB: ${{ matrix.database-name }}
        run: pytest -v -s
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v4
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"